### ISSUE TITLE
Cannot find ['Id'] primary key(s) in record

### ISSUE THREAD

**Issue by pavneet9** [jmriego/pipelinewise-target-bigquery-old#3]
I ma trying to connect this to tap-salesforce but this is the error I am getting.

`time=2020-06-11 17:51:05 name=singer level=INFO message=Cannot find ['Id'] primary key(s) in record: {'id': '00Q0b00001m9ntzEAA', 'isdeleted': False, 'masterrecordi
d': None, 'lastname': 'Lead', 'firstname': 'Test', 'salutation': 'Mr.', 'name': 'Test Lead', 'title': None, 'company': 'Leadly', 'street': None, 'city': None, 'stat
e': None, 'postalcode': None, 'country': None, 'latitude': None, 'longitude': None, 'geocodeaccuracy': None, 'phone': None, 'mobilephone': None, 'fax': None, 'email
': None, 'website': None, 'photourl': '/services/images/photo/00Q0b00001m9ntzEAA', 'description': None, 'leadsource': None, 'status': 'Open - Not Contacted', 'indus
try': None, 'rating': None, 'annualrevenue': None, 'numberofemployees': None, 'ownerid': '0050b000005E9hUAAS', 'isconverted': False, 'converteddate': None, 'convert
edaccountid': None, 'convertedcontactid': None, 'convertedopportunityid': None, 'isunreadbyowner': False, 'createddate': datetime.datetime(2020, 6, 11, 0, 59, 51, t
zinfo=tzlocal()), 'createdbyid': '0050b000005E9hUAAS', 'lastmodifieddate': datetime.datetime(2020, 6, 11, 0, 59, 51, tzinfo=tzlocal()), 'lastmodifiedbyid': '0050b00
0005E9hUAAS', 'systemmodstamp': datetime.datetime(2020, 6, 11, 0, 59, 51, tzinfo=tzlocal()), 'lastactivitydate': None, 'lastvieweddate': datetime.datetime(2020, 6, 
11, 0, 59, 53, tzinfo=tzlocal()), 'lastreferenceddate': datetime.datetime(2020, 6, 11, 0, 59, 53, tzinfo=tzlocal()), 'jigsaw': None, 'jigsawcontactid': None, 'clean
status': 'Pending', 'companydunsnumber': None, 'dandbcompanyid': None, 'emailbouncedreason': None, 'emailbounceddate': None, 'siccode__c': None, 'productinterest__c
': None, 'primary__c': None, 'currentgenerators__c': None, 'numberoflocations__c': None}`

**Comment by jmriego** [comment]
can you check the exact name of the id column in the table?

The Salesforce tap is saying that the primary key is the field `Id` but the list of columns in that table seem to be `id`, `isdeleted`, `masterrecordi d`...

Notice the difference in the case of the column naming. At first check it seems to be an error in the tap-salesforce instead but let's try to figure out properly

**Comment by pavneet9** [comment]
Hey Jm,

According to me, the issue arises from the fact that the code when it creates a table based on the default schema it makes everything lowercase.

Also, I think the record are also made into lowercase, using a flatten function.

 `def flatten_key(k, parent_key, sep):
    full_key = parent_key + [k]
    inflected_key = full_key.copy()
    reducer_index = 0
    while len(sep.join(inflected_key)) >= 255 and reducer_index < len(inflected_key):
        reduced_key = re.sub(r'[a-z]', '', inflection.camelize(inflected_key[reducer_index]))
        inflected_key[reducer_index] = \
            (reduced_key if len(reduced_key) > 1 else inflected_key[reducer_index][0:3]).lower()
        reducer_index += 1

    return sep.join(inflected_key)`

But the primary key that is brought from the catalog file is not made lower case.

`    def record_primary_key_string(self, record):
        if len(self.stream_schema_message['key_properties']) == 0:
            return None
        flatten = flatten_record(record, max_level=self.data_flattening_max_level)
        try:
            key_props = [str(flatten[p]) for p in self.stream_schema_message['key_properties']]
        except Exception as exc:
            logger.info("Cannot find {} primary key(s) in record: {}".format(self.stream_schema_message['key_properties'], flatten))
            raise exc
        return ','.join(key_props)`

This is the function giving the error. 

I wanted to fork and actually solve it, but I just bypassed it by changing the catalog file of tap-salesforce. Their I just made the primary key field to be lowercase. All the keys from salesforce have their first letter capital. But the big query schema is coming out with all small letters.

This is my thought process, I am using the tap-salesforce from pipelinewise also. Let me know if you need anything from my side.

**Comment by jmriego** [comment]
that was fast! yes, I think you are right. I'm going to have a look at this and upload some changes on this weekend

**Comment by jmriego** [comment]
I've done some quick fix in the `development` branch if you want to have a look for now. I'll do some further testing before this is closed. If you want to have a look and find anything, please let me know

**Comment by pavneet9** [comment]
Worked for me the changed you made. On a separate note, My state.json file is not being outputted properly. I am pretty sure this is related to the tap -salesforce, but just wanted to run it by you

`{"current_stream": null, "bookmarks": {"Lead": {"version": null}}}
{"current_stream": null, "bookmarks": {"Lead": {"version": null}}}`

**Comment by koszti** [comment]
this has been merged. Do you want to have a new release on PyPI (1.0.1) with this fix?

**Comment by jmriego** [comment]
thanks a lot @koszti ! Yes, I think that would make sense. How does that work? Should next time I do a pull request update the version in the setup file or something like that?

**Comment by koszti** [comment]
sure you can do this time as well :) Bump the version in setup.py, edit changelog.md and add what has changed and send a PR. ;)

Once it got merged the new version will be published to pypi automatically

**Comment by jmriego** [comment]
Sure thing, I'll send the merge request now. Thanks!

**Comment by koszti** [comment]
done. 1.0.1 is now available on pypi at https://pypi.org/project/pipelinewise-target-bigquery/
